// Browser presentation over the same APIs, content and account used by the Mini App.
window.NastaunikSite={ready:fetch('/site/auth/me',{credentials:'same-origin',cache:'no-store'}).then(r=>r.ok?r.json():{}).then(data=>{window.NASTAUNIK_SITE_CSRF=data.csrf||null;return data}).catch(()=>({authenticated:false}))};
const siteTabs=[['home','⌂','Главная','/'],['library','▤','Библиотека','/library'],['tracks','◇','Треки','/tracks'],['consultations','♡','Консультации','/consultations'],['profile','○','Профиль','/profile']];
let siteRouting=false;
function sitePath(path){if(!siteRouting&&location.pathname+location.search!==path)history.pushState({},'',path)}
const mobileNav=nav;
nav=()=>`<aside class="site-sidebar" aria-label="Навигация сайта"><span class="site-menu-label">Пространство клуба</span><nav>${siteTabs.map(([key,icon,label,path])=>`<a href="${path}" class="${state.tab===key?'active':''}" ${state.tab===key?'aria-current="page"':''} onclick="event.preventDefault();go('${key}')"><span aria-hidden="true">${icon}</span>${label}</a>`).join('')}</nav><div class="site-sidebar-note"><span>Учитесь в своём темпе.</span><small>Материалы, практика и поддержка — всё рядом.</small></div></aside>${mobileNav()}`;
const siteBaseShell=shell;
shell=content=>{if(content.includes('class="lesson-top"')&&state.currentCourse?.lessons)content=`<div class="site-lesson-layout"><div class="site-lesson-body">${content}</div><aside class="site-lesson-outline"><span class="eyebrow">Программа курса</span><h2>${esc(state.currentCourse.title)}</h2>${courseProgram(state.currentCourse)}</aside></div>`;siteBaseShell(content);const header=document.createElement('header');header.className='site-header';header.innerHTML=`<a class="site-logo" href="/" onclick="event.preventDefault();go('home')"><span>✦</span> Nastaŭnik</a><span class="site-header-caption">Клуб для учителей</span><div class="site-account">${state.data&&!state.data.user.guest?`<button class="site-user" onclick="go('profile')">${esc(state.data.user.first_name||'Мой профиль')}</button><button class="site-signout" onclick="siteLogout()">Выйти</button>`:'<button class="button" onclick="siteLogin()">Войти через Telegram</button>'}</div>`;document.getElementById('app').prepend(header);if(!document.querySelector('.site-sidebar'))document.querySelector('main.shell')?.insertAdjacentHTML('beforeend',nav())};
const webHome=home;home=()=>{if(!state.data.user.guest)return webHome();return `<section class="site-welcome"><span class="eyebrow">Ваше пространство для обучения</span><h1>Новые идеи.<br>Уверенная практика.</h1><p>Материалы, курсы и понятные маршруты для учителей. Изучайте инструменты, пробуйте на своих задачах и получайте поддержку клуба.</p><div class="site-welcome-actions"><button class="button" onclick="go('library')">Открыть библиотеку →</button><button class="button secondary" onclick="siteLogin()">Войти через Telegram</button></div><small>Есть аккаунт в Mini App? Войдите через тот же Telegram — ваш прогресс уже здесь.</small></section><section class="site-highlights"><button onclick="go('library')"><span>▤</span><h2>Знания под рукой</h2><p>Материалы для быстрых ответов и курсы для глубокого изучения.</p></button><button onclick="go('tracks')"><span>◇</span><h2>Понятный путь</h2><p>Выберите трек, двигайтесь по шагам и в удобном темпе.</p></button><button onclick="go('consultations')"><span>♡</span><h2>Личная поддержка</h2><p>Запишитесь на консультацию и разберите свою задачу.</p></button></section><div class="section-head"><h2>В библиотеке клуба</h2><button class="back" onclick="go('library')">Посмотреть всё →</button></div><div class="grid">${state.data.materials.slice(0,4).map(materialCard).join('')||'<section class="card empty">Новые материалы появятся здесь.</section>'}</div>${nav()}`};
const webBanner=freeAccessBanner;freeAccessBanner=()=>state.data?.user?.guest?'':webBanner();
const webProfile=profile;profile=()=>state.data.user.guest?`<section class="hero site-profile-login"><span class="eyebrow">Ваш аккаунт клуба</span><h1>Продолжайте с того места,<br>где остановились.</h1><p>Войдите через Telegram, чтобы увидеть подписку, сохранить прогресс и пользоваться всеми возможностями своего аккаунта.</p><button class="button" onclick="siteLogin()">Войти через Telegram</button><p>Если вы уже пользовались Mini App, выберите тот же аккаунт Telegram.</p></section>${nav()}`:webProfile();
const webMembership=window.openMembership;window.openMembership=()=>state.data?.user?.guest?siteLogin():webMembership();
const webGo=window.go;window.go=tab=>{sitePath(siteTabs.find(t=>t[0]===tab)?.[3]||(tab==='courses'?'/library?type=courses':'/'));return webGo(tab)};
const webMaterial=window.openMaterial;window.openMaterial=async id=>{await webMaterial(id);if(!state.data.materials.find(m=>m.id===id)?.locked)sitePath(`/material/${id}`)};
const webCourse=window.openCourse;window.openCourse=async(id,resume=false)=>{await webCourse(id,resume);if(!state.data.courses.find(c=>c.id===id)?.locked&&!resume)sitePath(`/course/${id}`)};
const webLesson=window.openCourseLesson;window.openCourseLesson=async(cid,lid)=>{if(!state.testMode)state.currentCourse=await api(`/course/${cid}`);await webLesson(cid,lid);sitePath(`/course/${cid}/lesson/${lid}`)};
const webTrack=window.openTrack;window.openTrack=async id=>{await webTrack(id);sitePath(`/track/${id}`)};
const webSelectTrack=window.selectTrack;window.selectTrack=(id,b)=>state.data.user.guest?siteLogin():webSelectTrack(id,b);
const webPreferences=window.openTrackPreferences;window.openTrackPreferences=intent=>state.data.user.guest?siteLogin():webPreferences(intent);
const webFinishMaterial=finishMaterial;finishMaterial=id=>{if(state.data.user.guest){updateCachedMaterial(id,{viewed:true});return Promise.resolve({ok:true,viewed:true,guest:true})}return webFinishMaterial(id)};
const webMaterialLike=window.toggleMaterialLike;window.toggleMaterialLike=id=>state.data.user.guest?siteLogin():webMaterialLike(id);
const webCourseLike=window.toggleCourseLike;window.toggleCourseLike=id=>state.data.user.guest?siteLogin():webCourseLike(id);
const webCompleteLesson=window.completeCourseLesson;window.completeCourseLesson=(cid,lid,b)=>state.data.user.guest?siteLogin():webCompleteLesson(cid,lid,b);
const webVideoAnalytics=wireCourseVideoAnalytics;wireCourseVideoAnalytics=(cid,lid)=>{if(!state.data.user.guest)webVideoAnalytics(cid,lid)};
const webTestAnswer=window.answerCourseTest;if(webTestAnswer)window.answerCourseTest=(...args)=>state.data.user.guest?siteLogin():webTestAnswer(...args);

function siteCloseLogin(){document.getElementById('site-login')?.close()}
window.siteLogin=async()=>{
 if(document.getElementById('site-login'))return;
 const dialog=document.createElement('dialog');dialog.id='site-login';dialog.className='site-login';dialog.innerHTML=`<div class="section-head"><h2>Войти в клуб</h2><button class="back" onclick="siteCloseLogin()" aria-label="Закрыть">×</button></div><p>Ваш Telegram — это ваш аккаунт клуба. Подписка и прогресс будут общими с Mini App.</p><div id="site-login-start" role="status">Готовим вход…</div><a id="site-telegram-link" class="button" target="_blank" rel="noopener" hidden>1. Получить код в Telegram ↗</a><form id="site-code-form" hidden><label for="site-code">2. Введите код из сообщения бота</label><input id="site-code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" minlength="6" placeholder="000000" required><p id="site-code-status" role="status"></p><button class="button" type="submit">Войти</button></form><small>Откройте бота по кнопке и нажмите «Запустить». Вернитесь сюда и введите шесть цифр. Пароль Telegram не нужен.</small>`;
 document.body.append(dialog);dialog.showModal();dialog.addEventListener('close',()=>dialog.remove());
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button'),status=dialog.querySelector('#site-code-status');b.disabled=true;status.textContent='Проверяем код…';try{const r=await fetch('/site/auth/finish',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:dialog.querySelector('input').value})});if(!r.ok)throw Error(await r.text());await r.json();location.reload()}catch(e){status.textContent=e.message;b.disabled=false}};
 try{const r=await fetch('/site/auth/start',{method:'POST',credentials:'same-origin'});if(!r.ok)throw Error(await r.text());const data=await r.json();if(!dialog.isConnected)return;const link=dialog.querySelector('#site-telegram-link');link.href=data.telegram_url;link.hidden=false;dialog.querySelector('form').hidden=false;dialog.querySelector('#site-login-start').textContent='Код действует 10 минут.'}catch(e){if(dialog.isConnected)dialog.querySelector('#site-login-start').textContent=e.message||'Не удалось начать вход. Закройте окно и попробуйте ещё раз.'}
};
window.siteLogout=async()=>{const r=await fetch('/site/auth/logout',{method:'POST',credentials:'same-origin',headers:{'X-Nastaunik-CSRF':window.NASTAUNIK_SITE_CSRF||''}});if(r.ok)location.href='/';else alert('Не удалось выйти. Обновите страницу и повторите.')};
async function siteRoute(){siteRouting=true;try{const path=location.pathname;let m;if((m=path.match(/^\/material\/(\d+)\/?$/))){state.tab='library';await openMaterial(Number(m[1]))}else if((m=path.match(/^\/course\/(\d+)\/lesson\/(\d+)\/?$/))){state.tab='library';await openCourse(Number(m[1]));await openCourseLesson(Number(m[1]),Number(m[2]))}else if((m=path.match(/^\/course\/(\d+)\/?$/))){state.tab='library';await openCourse(Number(m[1]))}else if((m=path.match(/^\/track\/(\d+)\/?$/))){await openTrack(Number(m[1]))}else{const tab=siteTabs.find(t=>t[3].replace(/\/$/,'')===path.replace(/\/$/,''))?.[0]||'home';if(tab==='library'&&new URLSearchParams(location.search).get('type')==='courses')state.libraryType='courses';await go(tab)}}catch(e){shell(`<section class="card empty"><h2>Не удалось открыть страницу</h2><p>${esc(e.message)}</p><button class="button" onclick="go('library')">Перейти в библиотеку</button></section>`)}finally{siteRouting=false}}
const webStartRoute=startRoute;startRoute=()=>{if(location.pathname!=='/'&&location.pathname!=='/site/'&&!location.pathname.startsWith('/mini-app/'))setTimeout(siteRoute,0);else webStartRoute()};
window.addEventListener('popstate',siteRoute);
